<a href="https://colab.research.google.com/github/Guava99/llm_journey/blob/main/CampusX_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id','Unnamed: 32'],inplace = True)

In [ ]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

train test split

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

Scaling

In [ ]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [ ]:
X_train

array([[-0.34740444,  0.74640316, -0.25138489, ...,  1.3084798 ,
         0.82612049,  2.18675215],
       [ 0.06651977,  2.05237211,  0.06333012, ..., -0.46952987,
        -1.63243321, -0.32832994],
       [ 0.91819118,  1.88676011,  0.86846522, ...,  0.65890827,
         0.1827152 ,  0.35770022],
       ...,
       [-0.39207252,  1.10365192, -0.36233381, ...,  0.90673058,
         0.78722445,  1.03613194],
       [-0.50225379, -0.62817647, -0.51343155, ..., -0.4016481 ,
        -0.45258674, -0.42982333],
       [ 0.14096657,  1.37572878,  0.20406687, ...,  0.1201641 ,
         0.46957348,  0.99271231]])

In [ ]:
Y_train

229    M
238    B
460    M
30     M
17     M
      ..
178    B
89     B
64     M
74     B
541    B
Name: diagnosis, Length: 455, dtype: object

In [ ]:
encoder=LabelEncoder()
Y_train=encoder.fit_transform(Y_train)
Y_test=encoder.transform(Y_test)

In [ ]:
Y_train

array([1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0])

Numpy arrays to PyTorch tensors

In [ ]:
X_train_tensor=torch.from_numpy(X_train).float()
X_test_tensor=torch.from_numpy(X_test).float()
Y_train_tensor=torch.from_numpy(Y_train).float()
Y_test_tensor=torch.from_numpy(Y_test).float()

In [ ]:
X_train_tensor.shape
# Y_train_tensor.shape

torch.Size([455, 30])

Defining the model

In [ ]:
import torch
import torch.nn as nn
class MySimpleNN(nn.Module):

  # def __init__(self,X):
  def __init__(self,num_features):
    super().__init__()  # VERY IMPORTANT

    #  self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    #  self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()
  def forward(self,X):
    #  z=torch.matmul(X,self.weights)+self.bias
    #  y_pred=torch.sigmoid(z)
    out=self.linear(X)
    out=self.sigmoid(out)
    return out
    # return y_pred
  # def loss_function(self, y_pred, y):
  #   # Clamp predictions to avoid log(0)
  #   epsilon = 1e-7
  #   y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

  #   # Calculate loss
  #   loss = -(Y_train_tensor * torch.log(y_pred) + (1 - Y_train_tensor) * torch.log(1 - y_pred)).mean()
  #   return loss

**Important Parameters**

In [ ]:
learning_rate=0.1
epochs=51

In [ ]:
loss_function=nn.BCELoss()

**Training** **Pipeline**

In [ ]:
#create model
# model=MySimpleNN(X_train_tensor)
model=MySimpleNN(X_train_tensor.shape[1])
# define optimizer
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)
#define loop
for epoch in range(epochs):
   #forward pass
   y_pred=model(X_train_tensor)



   #loss calculate
  #  loss= model.loss_function(y_pred,Y_train_tensor)
   loss=loss_function(y_pred,Y_train_tensor.view(-1,1))

   optimizer.zero_grad()

   #backward pass

   loss.backward()
   #parameters update

   with torch.no_grad():
    # model.weights-=learning_rate*model.weights.grad
    # model.bias-=learning_rate*model.bias.grad
    #------------
    # model.linear.weight-=learning_rate*model.linear.weight.grad
    # model.linear.bias-=learning_rate*model.linear.bias.grad
    #-------------
    optimizer.step()
   #zero gradients
  #  model.linear.weight.grad.zero_()
  #  model.linear.bias.grad.zero_()
  #--------------

   # print loss in each epoch
   print(f'Epoch:{epoch+1},Loss:{loss.item()}')

Epoch:1,Loss:0.6672741770744324
Epoch:2,Loss:0.5166104435920715
Epoch:3,Loss:0.4343472719192505
Epoch:4,Loss:0.3822382986545563
Epoch:5,Loss:0.3458360731601715
Epoch:6,Loss:0.31869152188301086
Epoch:7,Loss:0.29749777913093567
Epoch:8,Loss:0.28037893772125244
Epoch:9,Loss:0.26618754863739014
Epoch:10,Loss:0.2541796863079071
Epoch:11,Loss:0.24385026097297668
Epoch:12,Loss:0.23484323918819427
Epoch:13,Loss:0.22689971327781677
Epoch:14,Loss:0.21982651948928833
Epoch:15,Loss:0.21347612142562866
Epoch:16,Loss:0.2077338695526123
Epoch:17,Loss:0.20250901579856873
Epoch:18,Loss:0.1977287083864212
Epoch:19,Loss:0.19333365559577942
Epoch:20,Loss:0.18927520513534546
Epoch:21,Loss:0.1855127513408661
Epoch:22,Loss:0.18201236426830292
Epoch:23,Loss:0.17874523997306824
Epoch:24,Loss:0.17568686604499817
Epoch:25,Loss:0.1728161722421646
Epoch:26,Loss:0.1701149046421051
Epoch:27,Loss:0.16756728291511536
Epoch:28,Loss:0.1651594191789627
Epoch:29,Loss:0.16287924349308014
Epoch:30,Loss:0.16071592271327972
Epoch:31,Loss:0.15866000950336456
Epoch:32,Loss:0.15670305490493774
Epoch:33,Loss:0.1548374444246292
Epoch:34,Loss:0.15305641293525696
Epoch:35,Loss:0.1513538509607315
Epoch:36,Loss:0.14972427487373352
Epoch:37,Loss:0.14816269278526306
Epoch:38,Loss:0.1466645896434784
Epoch:39,Loss:0.1452258676290512
Epoch:40,Loss:0.14384274184703827
Epoch:41,Loss:0.14251181483268738
Epoch:42,Loss:0.14122991263866425
Epoch:43,Loss:0.13999420404434204
Epoch:44,Loss:0.13880197703838348
Epoch:45,Loss:0.13765083253383636
Epoch:46,Loss:0.13653847575187683
Epoch:47,Loss:0.13546282052993774
Epoch:48,Loss:0.1344219595193863
Epoch:49,Loss:0.13341407477855682
Epoch:50,Loss:0.13243749737739563
Epoch:51,Loss:0.13149067759513855

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  # print(y_pred)
  y_pred=(y_pred>0.5).float()
  accuracy=(y_pred== Y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')