<a href="https://colab.research.google.com/github/Guava99/llm_journey/blob/main/campusx_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id','Unnamed: 32'],inplace = True)

In [ ]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

train test split

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

Scaling

In [ ]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [ ]:
X_train

array([[ 1.65500927e-01,  1.38905968e+00,  1.04883491e-01, ...,
        -7.99634057e-02, -3.04793724e-01, -8.10683471e-01],
       [ 2.50734108e+00,  1.15211986e-01,  2.44040703e+00, ...,
         1.69271043e+00, -3.05819117e-04, -6.32030000e-01],
       [ 3.36847748e-02,  7.35044855e-01,  6.70431271e-02, ...,
         3.24915906e-01, -3.44082486e-01, -3.42922191e-02],
       ...,
       [ 2.20444439e+00,  5.86923030e-01,  2.24103307e+00, ...,
         1.94746595e+00, -2.73690121e-01,  8.98190707e-02],
       [-1.22642155e+00, -5.31966452e-01, -1.20528825e+00, ...,
        -9.31574721e-01, -6.14192724e-01,  3.08244666e-02],
       [ 5.33169676e-02, -1.33410311e+00,  1.57755373e-02, ...,
        -9.20946210e-02,  2.51797070e-01, -1.30267621e+00]])

In [ ]:
Y_train

542    B
503    M
536    M
360    B
462    B
      ..
480    B
468    M
369    M
110    B
225    B
Name: diagnosis, Length: 455, dtype: object

In [ ]:
encoder=LabelEncoder()
Y_train=encoder.fit_transform(Y_train)
Y_test=encoder.transform(Y_test)

In [ ]:
Y_train

array([0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0])

Numpy arrays to PyTorch tensors

In [ ]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
Y_train_tensor=torch.from_numpy(Y_train)
Y_test_tensor=torch.from_numpy(Y_test)

In [ ]:
X_train_tensor.shape
# Y_train_tensor.shape

torch.Size([455, 30])

Defining the model

In [ ]:
class MySimpleNN():
  def __init__(self,X):
     self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
     self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)
  def forward(self,X):
     z=torch.matmul(X,self.weights)+self.bias
     y_pred=torch.sigmoid(z)
     return y_pred
  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(Y_train_tensor * torch.log(y_pred) + (1 - Y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

**Important Parameters**

In [ ]:
learning_rate=0.1
epochs=51

**Training** **Pipeline**

In [ ]:
#create model
model=MySimpleNN(X_train_tensor)
#define loop
for epoch in range(epochs):
   #forward pass
   y_pred=model.forward(X_train_tensor)

   #loss calculate
   loss= model.loss_function(y_pred,Y_train_tensor)

   #backward pass
   loss.backward()
   #parameters update
   with torch.no_grad():
    model.weights-=learning_rate*model.weights.grad
    model.bias-=learning_rate*model.bias.grad
   #zero gradients
   model.weights.grad.zero_()
   model.bias.grad.zero_()

   # print loss in each epoch
   print(f'Epoch:{epoch+1},Loss:{loss.item()}')

Epoch:1,Loss:3.338447243727961
Epoch:2,Loss:3.204858999795708
Epoch:3,Loss:3.0692115020934883
Epoch:4,Loss:2.9312939416113224
Epoch:5,Loss:2.787950106785955
Epoch:6,Loss:2.641264916394964
Epoch:7,Loss:2.49533313373886
Epoch:8,Loss:2.3502040003696507
Epoch:9,Loss:2.206829445711805
Epoch:10,Loss:2.0680597934586604
Epoch:11,Loss:1.926902825152103
Epoch:12,Loss:1.7900746381482473
Epoch:13,Loss:1.6622724969358833
Epoch:14,Loss:1.5442639816758266
Epoch:15,Loss:1.430631829360484
Epoch:16,Loss:1.327770048203251
Epoch:17,Loss:1.2347268898946029
Epoch:18,Loss:1.1531311878119064
Epoch:19,Loss:1.0848083415252283
Epoch:20,Loss:1.0287494865187738
Epoch:21,Loss:0.9834111811679026
Epoch:22,Loss:0.9469528848953658
Epoch:23,Loss:0.917520175405847
Epoch:24,Loss:0.8934576799408949
Epoch:25,Loss:0.8734159999050104
Epoch:26,Loss:0.8563694708207091
Epoch:27,Loss:0.841577808166556
Epoch:28,Loss:0.8285242885805835
Epoch:29,Loss:0.8168535967053931
Epoch:30,Loss:0.8063205961269315
Epoch:31,Loss:0.796752644243957
Epoch:32,Loss:0.788023810443051
Epoch:33,Loss:0.7800380812065419
Epoch:34,Loss:0.772718785524158
Epoch:35,Loss:0.7660020897568905
Epoch:36,Loss:0.7598330511315053
Epoch:37,Loss:0.7541632325634763
Epoch:38,Loss:0.7489492479765248
Epoch:39,Loss:0.7441518517107828
Epoch:40,Loss:0.7397353414818785
Epoch:41,Loss:0.7356671405131623
Epoch:42,Loss:0.7319174822132817
Epoch:43,Loss:0.7284591546416599
Epoch:44,Loss:0.7252672814269149
Epoch:45,Loss:0.7223191266867034
Epoch:46,Loss:0.719593917441633
Epoch:47,Loss:0.7170726801625523
Epoch:48,Loss:0.714738089687936
Epoch:49,Loss:0.7125743295099323
Epoch:50,Loss:0.7105669627545981
Epoch:51,Loss:0.7087028132944911

In [ ]:
model.weights

tensor([[ 0.4213],
        [ 0.4389],
        [ 0.5222],
        [-0.1509],
        [ 0.1506],
        [-0.1876],
        [ 0.0709],
        [-0.4483],
        [ 0.3835],
        [ 0.0539],
        [ 0.1710],
        [ 0.2231],
        [ 0.1906],
        [ 0.0225],
        [ 0.2177],
        [-0.3191],
        [ 0.2509],
        [-0.4453],
        [-0.3334],
        [ 0.2579],
        [-0.3080],
        [-0.4020],
        [ 0.1550],
        [-0.2802],
        [-0.1132],
        [ 0.1094],
        [-0.1116],
        [-0.0620],
        [-0.0208],
        [ 0.1296]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.bias

tensor([-0.2988], dtype=torch.float64, requires_grad=True)

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  # print(y_pred)
  y_pred=(y_pred>0.5).float()
  accuracy=(y_pred== Y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.586334228515625

In [ ]:
!git push

fatal: not a git repository (or any of the parent directories): .git